# การเรียงลำดับแบบฟอง (Bubble Sort)

ในสาขาวิทยาการคอมพิวเตอร์ การเรียงลำดับแบบฟอง (อังกฤษ: bubble sort) เป็นขั้นตอนวิธีการเรียงลำดับที่เรียบง่ายมาก 

ดำเนินการบนโครงสร้างข้อมูลประเภทรายการ ทำงานโดยเปรียบเทียบสมาชิกที่อยู่ติดกัน เมื่อพบตำแหน่งที่ผิด (นั่นคือตัวหน้ามากกว่าตัวหลังในกรณีการเรียงจากน้อยไปมาก) 

ก็จะทำการสลับข้อมูลกัน และจะดำเนินการซ้ำแบบนี้ไปเรื่อยๆจนกว่าจะไม่มีตำแหน่งที่ผิดอีกซึ่งบ่งบอกว่ารายการนั้นเรียงแล้ว ชื่อของขั้นตอนวิธีนี้มีมาจากสมาชิกที่น้อยที่สุดจะค่อยๆถูกสลับขึ้นมาจนอยู่หน้าสุดของรายการ เปรียบได้กับฟองที่ค่อยๆผุดขึ้นมาถึงผิวน้ำ 

เนื่องจากขั้นตอนวิธีนี้ใช้เพียงการเปรียบเทียบจึงเป็นการเรียงแบบเปรียบเทียบ นอกจากนี้ยังเป็นการเรียงแบบเสถียรอีกด้วย ถึงแม้ว่าการเรียงลำดับแบบฟองจะเป็นขั้นตอนวิธีที่เรียบง่ายมาก แต่ไม่เหมาะในการเรียงข้อมูลจำนวนมากซึ่งมีวิธีการเรียงข้อมูลที่มีประสิทธิภาพมากกว่า

## ประสิทธิภาพ

ประสิทธิภาพของการเรียงลำดับแบบฟองขึ้นอยู่กับตำแหน่งของข้อมูลต่าง ๆ ที่อยู่ในรายการ หากมีค่ามากอยู่ตัวแรกๆ การเรียงลำดับแบบฟองจะมีประสิทธิภาพดี เพราะว่าการทำงานเพียงรอบเดียวก็สามารถทำให้ค่ามากไปอยู่ในตำแหน่งที่ใกล้เคียงกับตำแหน่งจริงได้ เช่น มีค่ามากที่สุดอยู่ในตำแหน่งแรก การทำงานรอบเดียวก็เพียงพอที่จะลากค่านั้นไปอยู่ตำแหน่งสุดท้ายได้ แต่กลับกันหากมีค่าน้อยอยู่หลังๆ 

การทำงานหนึ่งรอบจะสามารถเลื่อนค่านั้นมาด้านหน้าได้เพียงเล็กน้อย เช่นหากค่านั้นเป็นค่าน้อยที่สุดการทำงานหนึ่งรอบจะเลื่อนค่านั้นมาด้านหน้าได้เพียงหนึ่งตำแหน่งเท่านั้น

การปรับปรุงประสิทธิภาพของการเรียงลำดับแบบฟองนั้นวิธีการหนึ่งก็คือการทำให้ค่าน้อยที่อยู่หลังๆ นั้นลงมาด้านหน้าได้เร็วขึ้น นั่นคือหลักการของ Cocktail Sort ซึ่งมีขั้นตอนวิธีคล้ายการเรียงลำดับแบบฟองมากเพียงแต่ทำงานทั้งขาไปและขากลับ ขาไปนั้นทำงานเหมือนการเรียงลำดับแบบฟองทุกประการ ส่วนขากลับก็เพียงกลับด้านของการเรียงลำดับแบบฟองนั่นเอง แต่การปรับปรุงดังนี้ก็ไม่ได้ทำให้ประสิทธิภาพในกรณีแย่ที่สุดดีกว่า O(n2) แต่อย่างใด

## สิ่งที่ต้องรู้ก่อนเรียนเรื่องการจัดเรียงลำดับ

### การสร้างลำดับตัวเลขเชิงสุ่ม

เพื่อเป็นการจำลองชุดข้อมูลขึ้นมาเพื่อใช้ทดสอบการเรียงลำดับนั้น เราจะทำการสร้างชุดข้อมูลตัวอย่างโดยการสุ่ม ซึ่งกระบวนการสร้างตัวเลขสุ่มมีดังต่อไปนี้

### 1. การสุ่มเลขจำนวนเต็ม

In [2]:
import numpy as np

In [3]:
lt = np.random.randint(1, 20, size=10)
lt

array([ 3, 12, 18, 10,  3,  1,  5, 18,  1,  7])

### 2. การสุ่มเลขจำนวนเต็มแบบไม่ซ้ำ

In [59]:
arr = np.random.choice(list(range(1, 21)), size=10, replace=False)
arr

array([17, 16,  9,  5,  3, 18,  1, 12, 20,  7])

### 3. การสุ่มเพื่อให้ได้ชุดตัวเลขเดิมทุกครั้ง

In [17]:
np.random.seed(10)

lt = np.random.randint(1, 20, size=10)
lt

array([10,  5, 16,  1, 18, 17, 18,  9, 10,  1])

### ตัวอย่างโปรแกรมเรียงลำดับแบบฟอง (Bubble Sort)

กลไกของการเรียงลำดับแบบฟองไปกอบไปด้วย

1. การจับคู่เปรียบเที่ยบระหว่างข้อมูลตัวที่ i และ i + 1
1. ในแต่ละรอบจะมีการจับคู่เปรียบเทียบทั้งหมด n - 1 ครั้ง
1. การสลับลำดับข้อมูล (Swap)
1. หากรอบใดไม่มีการ Swap โปรแกรมจะหยุดทำงาน

<img src="./imgs/bubblepass.png">

In [62]:
import numpy as np

def bubbleSort(lt):
    swap = True
    while swap:
        swap = False
        for i in range(0, len(lt)-1):
            if lt[i] > lt[i+1]:
                lt[i], lt[i+1] = lt[i+1], lt[i]
                swap = True
                

arr = np.random.choice(list(range(1, 21)), size=10, replace=False)

print("Before sort : {}".format(arr))
bubbleSort(arr)
print("After sorted : {}".format(arr))


Before sort : [ 6  9 15  7 12 18 11  2  8 17]
After sorted : [ 2  6  7  8  9 11 12 15 17 18]


<hr />

# การเรียงลำดับแบบเลือก : The Selection Sort

ในสาขาวิทยาการคอมพิวเตอร์ การเรียงลำดับแบบเลือก (อังกฤษ: selection sort) เป็นขั้นตอนวิธีการเรียงลำดับอย่างง่ายโดยใช้วิธีการเปรียบเทียบ ทำงานโดยการหาค่าเหมาะสมที่สุด (ค่ามากสุดหรือน้อยสุด) ที่อยู่ในรายการส่วนที่ยังไม่เรียงและนำค่าเหมาะที่สุดนั้นมาต่อท้ายของส่วนที่เรียงแล้ว ก็จะทำให้ส่วนที่เรียงแล้วมีขนาดใหญ่ขึ้นทีละหนึ่งในแต่ละรอบการทำงาน ทำเช่นนี้จนไม่มีส่วนที่ยังไม่เรียงก็เสร็จ 

แต่ด้วยประสิทธิภาพเมื่อเกิดกรณีทั่วไปที่ O(n2) ทำให้ไม่เหมาะที่จะใช้ในกรณีที่มีข้อมูลในรายการเป็นจำนวนมาก แต่ถ้าหากปรับปรุงการหาค่าเหมาะสมที่สุดในรายการด้วยแถวคอยลำดับความสำคัญที่ทำให้เกิดผลด้วยโครงสร้างข้อมูลแบบฮีปทวิภาคจะเรียกว่าการเรียงลำดับแบบฮีป ซึ่งมีประสิทธิภาพดีกว่าที่ O(n log n)

การเรียงลำดับการเลือกปรับปรุงในการจัดเรียงฟอง โดยทำการแลกเปลี่ยนเพียงครั้งเดียวสำหรับทุก ๆ การส่งผ่านรายการ 

ในการทำเช่นนี้การเรียงลำดับการเลือกจะค้นหาค่าที่มากที่สุดเมื่อทำการส่งผ่านและหลังจากผ่านการวางแล้วให้วางลงในตำแหน่งที่เหมาะสม เช่นเดียวกับการจัดเรียงฟองหลังจากผ่านครั้งแรกรายการที่ใหญ่ที่สุดอยู่ในสถานที่ที่ถูกต้อง 

หลังจากผ่านไปครั้งที่สองที่ใหญ่ที่สุดถัดไปอยู่ในสถานที่ กระบวนการนี้ดำเนินต่อไปและต้องการ n − 1

<img src="./imgs/selectionsortnew.png">

### ตัวอย่างโปรแกรม การเรียงลำดับแบบเลือก

In [61]:
import numpy as np

def selectionSort(lt):
    for top in range(len(lt)-1 , -1, -1):
        max_index = 0
        for i in range(1, top+1):
            if lt[max_index] <= lt[i]:
                max_index = i

        #swap
        lt[top], lt[max_index] = lt[max_index], lt[top]
        
arr = np.random.choice(list(range(1, 21)), size=10, replace=False)

print("Before sort : {}".format(arr))
selectionSort(arr)
print("After sorted : {}".format(arr))

Before sort : [14 20  5 13 16 15 17  7  4  3]
After sorted : [ 3  4  5  7 13 14 15 16 17 20]
